Send events to imgui only if imgui need to capture them
Lugdunum3D/Lugdunum pull request #105
Opened 2017-11-08 20:59 UTC by Nokitoo

2017-11-09 12:44 UTC, yoannpicquenot submitted a review, later dismissed

2017-11-09 21:49 UTC, Quentin01 requested changes

2017-11-09 21:49 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +        else if (!value) {
Why didn't you check directly the call to `_impl->pollEvent` and returning false directly?

2017-11-09 21:49 UTC, Quentin01 commented on src/lug/Graphics/Vulkan/Gui.cpp
> +    } else if (io.WantCaptureKeyboard) {
Isn't it possible for `io.WantCaptureMouse` and `io.WantCaptureKeyboard` to be `true` at the same time?

2017-11-23 22:27 UTC, Quentin01 approved these changes

2017-11-23 22:27 UTC, merged