Logging system
Lugdunum3D/Lugdunum pull request #11
Opened 2016-10-15 17:11 UTC by saveman71

Still WIP. No need to review as of now.

2016-12-17 20:58 UTC, Quentin01 requested changes

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    virtual ~Logger() {}
` = default` and do you really want to inherit from `Logger`? If not, just remove all virtual functions.

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    virtual ~Logger() {}
Define copy / move constructors / operators (can be `= delete`)

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    virtual void addHandler(Handler* handler) {
If you want to define functions in the header, define them in a `.inl` file

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    virtual void defaultErrHandler(const std::string& msg) {
Maybe take an exception in parameter and not a `std::string`? Is it okay for an user to use it?

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/Common.hpp
> +namespace Level {
What? Just use an `enum class Level` no?

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    inline void log(Level::enumLevel lvl, const T& fmt, const Args &... args) {
Use universal reference and forward them to `write`

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    inline void debug(const T& fmt, const Args&... args) {
Use universal reference and forward them

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    inline void info(const T& fmt, const Args&... args) {
Use universal reference and forward them

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    inline void warn(const T& fmt, const Args&... args) {
Use universal reference and forward them

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    inline void error(const T& fmt, const Args&... args) {
Use universal reference and forward them

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    inline void fatal(const T& fmt, const Args&... args) {
Use universal reference and forward them

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    inline void assrt(const T& fmt, const Args&... args) {
Use universal reference and forward them

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger.hpp
> +    inline void assrt(const T& fmt, const Args&... args) {
Maybe `assert`?

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/Common.hpp
> +namespace Channel {
What? Just use an `enum class Channel` no?

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/FileHandler.hpp
> +    FileHandler(const std::string& name, const filename_t& filename, bool truncate) : Handler(name) {
Don't put the content of methods in the header, or use a file `.inl` for that

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/FileHandler.hpp
> +    virtual ~FileHandler() {
Do you really want to inherit from that class? If not remove all the virtual functions.

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/FileHandler.hpp
> +class FileHandler : public Handler {
Don't you want to export it?

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/Formatter.hpp
> +    virtual ~Formatter () {};
`= default`

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/Formatter.hpp
> +
Remove the double vertical space

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/Handler.hpp
> +    Handler(const std::string& name);
Implement copy / move constructors / operators

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/LogCatHandler.hpp
> +    LogCatHandler(const std::string& name) : Handler(name) {
Indent correctly the brackets

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/LogCatHandler.hpp
> +    LogCatHandler(const std::string& name) : Handler(name) {
Don't put the content of methods in the header, or use a file `.inl` for that

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/LogCatHandler.hpp
> +    virtual ~LogCatHandler() {
`= default` and do you really want to inherit from that class?

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/Message.hpp
> +    Message(const std::string& _loggerName, Level::enumLevel _level): loggerName(_loggerName), level(_level) {
Indent correctly the brackets

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/OstreamHandler.hpp
> +    OstreamHandler(const std::string& name, std::ostream& out) : Handler(name), _os(out) {
Indent correctly the brackets

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/OstreamHandler.hpp
> +    virtual ~OstreamHandler() {
Indent correctly the brackets

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/FileHandler.hpp
> +class FileHandler : public Handler {
Why aren't you inheriting from `OstreamHandler` ?

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/Message.hpp
> +struct Message {
Don't you want to export it?

2016-12-17 20:58 UTC, Quentin01 commented on include/lug/System/Logger/LogCatHandler.hpp
> +class LogCatHandler : public Handler {
Don't you want to export it?

2016-12-17 20:58 UTC, Quentin01 commented on samples/base/main.cpp
> +int main(int, const char*[]) {
Remove all the useless comments and remove the `const` (It can be a problem in the future)

2016-12-17 20:58 UTC, Quentin01 commented on samples/base/main.cpp
> +int main(int, const char*[]) {
Maybe log the exception to demonstrate the logger?

2016-12-17 20:58 UTC, Quentin01 commented on samples/window/main.cpp
> +#include <lug/System/Logger/LogCatHandler.hpp>
Be sure to be on Android for that!

2016-12-17 20:58 UTC, Quentin01 commented on src/lug/System/CMakeLists.txt
> +    ${INCROOT}/Logger/LogCatHandler.hpp
Only for Android?

2016-12-17 20:58 UTC, Quentin01 commented on src/lug/System/Logger/Formatter.cpp
> +    // TODO: test on android
So, tested or not?

2016-12-17 20:58 UTC, Quentin01 commented on src/lug/System/Logger/Formatter.cpp
> +        else if (elem.basic) {
After the closing bracket

2016-12-17 20:58 UTC, Quentin01 commented on src/lug/System/Logger/Formatter.cpp
> +        else if (elem.advanced) {
After the closing bracket

2016-12-17 20:58 UTC, Quentin01 commented on src/lug/System/Logger/Handler.cpp
> +Handler::~Handler() {}
`= default`

2016-12-17 20:58 UTC, Quentin01 commented on src/lug/System/Logger/Logger.cpp
> +const std::string& Logger::getName() const {
Inline getters maybe

2016-12-17 20:58 UTC, Quentin01 commented on test/System/Logger/MockHandler.hpp
> +    MockHandler(const std::string& name) : Handler(name) {
Indent your brackets correctly

2016-12-17 20:58 UTC, Quentin01 commented on test/System/Logger/MockHandler.hpp
> +    virtual ~MockHandler() {
Do you really want to inherit from that class?

2016-12-18 00:02 UTC, Sumenia commented on include/lug/System/Logger/Message.hpp
> +}
specify the closing namespace in comment

2016-12-19 06:16 UTC, saveman71 commented on include/lug/System/Logger/Formatter.hpp
> +
Done

2016-12-19 06:16 UTC, saveman71 commented on include/lug/System/Logger/Handler.hpp
> +    Handler(const std::string& name);
Done

2016-12-19 07:50 UTC, Quentin01 approved these changes

2016-12-19 13:39 UTC, merged