Feature exception
Lugdunum3D/Lugdunum pull request #2
Opened 2016-10-02 08:29 UTC by Nokitoo

2016-10-02 19:16 UTC, Quentin01 requested changes
Some comments :)

2016-10-02 19:16 UTC, Quentin01 commented on include/lug/System/Exception.hpp
> +    Exception(Exception&& other);
Why are you not using "= default"? Because in the .cpp you just reimplement the default implementation.

2016-10-02 19:16 UTC, Quentin01 commented on include/lug/System/Exception.hpp
> +    const std::string&              getTypeName() const;
You don't need to have many spaces between the type and the member function name. (Guidelines)

2016-10-02 19:16 UTC, Quentin01 commented on include/lug/System/Exception.hpp
> +    const char*                     what() const;
You don't inherit from std::exception, so for what reason do you don't return a std::string to avoid the usage of _fullDesc?

2016-10-02 19:16 UTC, Quentin01 commented on include/lug/System/Exception.hpp
> +    Exception& operator=(const Exception&& other);
A left value reference can't be "const".

2016-10-02 19:16 UTC, Quentin01 commented on include/lug/System/Exception.hpp
> +class NotImplementedException: public Exception {
So, you don't export them?

2016-10-02 19:16 UTC, Quentin01 commented on src/lug/System/CMakeLists.txt
> +    ${INCROOT}/Exception.hpp
Alphabetic order please :)

2016-10-02 19:16 UTC, Quentin01 commented on src/lug/System/Exception.cpp
> +#include "../../../include/lug/System/Exception.hpp"
You just need to write `#include <lug/System/Exception.hpp>`
If you don't do it like that it won't work on the user side. Maybe try to compile the library and test it like an user?

2016-10-02 22:57 UTC, saveman71 commented on include/lug/System/Exception.hpp
> +class NotImplementedException: public Exception {
(i.e. add `LUG_SYSTEM_API` if that wasn't clear enough)

2016-10-02 22:57 UTC, saveman71 commented on src/lug/System/Exception.cpp
> +}
Same remark as above

2016-10-02 22:57 UTC, saveman71 commented on include/lug/System/Exception.hpp
> +}
Please add a `\n` at the end of the file. Configure your editor to do it for you.

In sublime text, the required settings for the project are:
```
{
    "tab_size": 4,
    "translate_tabs_to_spaces": true,
    "trim_trailing_white_space_on_save": true,
    "ensure_newline_at_eof_on_save": true,
}
```

2016-10-02 22:57 UTC, saveman71 commented on include/lug/System/Exception.hpp
> +  throw type(desc, __FILE__, __FUNCTION__, __LINE__);\
4 spaces

2016-10-02 22:57 UTC, saveman71 commented on include/lug/System/Exception.hpp
> +    const long                      getLine() const;
use uint32_t instead

2016-10-02 22:59 UTC, saveman71 commented on include/lug/System/Exception.hpp
> +class NotImplementedException: public Exception {
(i.e. add `LUG_SYSTEM_API` if that wasn't clear enough)

2016-10-03 03:06 UTC, saveman71 commented on include/lug/System/Exception.hpp
> +    const long getLine() const;
uint32_t

2016-10-03 03:06 UTC, saveman71 commented on include/lug/System/Exception.hpp
> +      throw type(desc, __FILE__, __FUNCTION__, __LINE__);\
I meant just 4 spaces just on the throw line

2016-10-03 04:27 UTC, Quentin01 requested changes

2016-10-03 04:27 UTC, Quentin01 commented on include/lug/System/Exception.hpp
> +    ~Exception() throw() {}
The destructor had to be virtual.

2016-10-03 04:27 UTC, Quentin01 commented on include/lug/System/Exception.hpp
> +      throw type(desc, __FILE__, __FUNCTION__, __LINE__);\
4 spaces * 2?
Maybe use `__PRETTY_FUNCTION__` (gcc & clang) and `__FUNCSIG__` (MSVC).

2016-10-03 08:26 UTC, saveman71 commented on include/lug/System/Exception.hpp
> +    const long getLine() const;
@Nokitoo FYI you forgot these in your latest commit

2016-10-03 09:07 UTC, Quentin01 requested changes

2016-10-03 09:07 UTC, Quentin01 commented on include/lug/System/Exception.hpp
> +#if defined(LUG_SYSTEM_WINDOWS)
Why not doing this near the other macro? And you are polluting the context, use undef to remove this useless macro after using it!

2016-10-03 10:19 UTC, Quentin01 approved these changes

2016-10-03 10:20 UTC, saveman71 approved these changes

2016-10-06 13:19 UTC, merged