Upload tests results on appveyor
Lugdunum3D/Lugdunum pull request #23
Opened 2016-11-25 18:35 UTC by cchardeau

2016-11-25 19:03 UTC, saveman71 commented
Can you explain the to-do?

2016-11-26 06:18 UTC, Quentin01 requested changes

2016-11-26 06:18 UTC, Quentin01 commented on appveyor.yml
> +    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test\System\SystemUnitTests.xml))
I think that you need to change the directory of output (with `TEST_OUTPUT`) and use a loop in that ps script to upload all the xml files.

2016-11-27 06:33 UTC, Quentin01 approved these changes

2016-11-27 06:34 UTC, merged