Feature window android
Lugdunum3D/Lugdunum pull request #24
Opened 2016-12-09 13:08 UTC by Sumenia

Deleting android/log until we have the cross platform logger
Deleting unnecessary events until we have uniform cross platform events

2016-12-09 14:02 UTC, Quentin01 requested changes

2016-12-09 14:02 UTC, Quentin01 commented on samples/window/CMakeLists.txt
> +    string(REPLACE ";" " " "CMAKE_CXX_FLAGS" "${CMAKE_CXX_FLAGS}")
Do that outside of the if. See https://github.com/Lugdunum3D/Lugdunum/blob/dev/samples/base/CMakeLists.txt#L30

2016-12-09 14:02 UTC, Quentin01 commented on samples/window/CMakeLists.txt
> +            )
Bad indentation

2016-12-09 14:02 UTC, Quentin01 commented on samples/window/CMakeLists.txt
> +            )
Bad indentation

2016-12-09 14:02 UTC, Quentin01 commented on samples/window/main.cpp
> +#include <string>
Remove that include

2016-12-09 14:02 UTC, Quentin01 commented on samples/window/main.cpp
> -
Why have you remove that line?

2016-12-09 14:02 UTC, Quentin01 commented on samples/window/main.cpp
> -
Why have you remove that line?

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Main/MainAndroid.hpp
> +extern std::queue<lug::Window::Event> events;
Why are you declaring them extern here? `MainAndroid.cpp` doesn't need that.

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Window/Android/WindowImplAndroid.cpp
> +lug::Window::priv::WindowImpl::WindowImpl(Window*) {}
You don't need to specify `lug::Window::priv::` here

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Window/Android/WindowImplAndroid.cpp
> +bool lug::Window::priv::WindowImpl::create(const std::string&, Style) {
You don't need to specify `lug::Window::priv::` here

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Window/Android/WindowImplAndroid.cpp
> +void lug::Window::priv::WindowImpl::close() {}
You don't need to specify `lug::Window::priv::` here

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Window/Android/WindowImplAndroid.cpp
> +bool lug::Window::priv::WindowImpl::pollEvent(lug::Window::Event& event) {
You don't need to specify `lug::Window::priv::` here

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Window/Android/WindowImplAndroid.cpp
> +            AInputQueue_finishEvent(lug::Main::inputQueue, androidEvent, handled);
Why not `AInputQueue_finishEvent(lug::Main::inputQueue, androidEvent, 0);` ?

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Window/Android/WindowImplAndroid.cpp
> +            int32_t handled = 0;
Maybe one vertical space?

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Window/Android/WindowImplAndroid.cpp
> +        while (AInputQueue_getEvent(lug::Main::inputQueue, &androidEvent) >= 0) {
Maybe one vertical space?

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Window/Android/WindowImplAndroid.hpp
> +#include <lug/Main/MainAndroid.hpp>
Do you really need that include? Can't you declare your extern here?

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Window/Android/WindowImplAndroid.hpp
> +private:
Remove that `private` if it isn't used

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Window/Android/WindowImplAndroid.hpp
> +} // namespace lug
New line at end of file

2016-12-09 14:02 UTC, Quentin01 commented on src/lug/Window/CMakeLists.txt
> +    list(APPEND EXT_LIBRARIES android)
Can't you append the two items in one line?

2016-12-09 14:05 UTC, Sumenia commented on src/lug/Main/MainAndroid.hpp
> +extern std::queue<lug::Window::Event> events;
I spent 1 hour trying to compile on android with the extern in lug/Window/Android/WindowImplAndroid.cpp with no success , ended up putting in here and it works

2016-12-09 14:09 UTC, Sumenia commented on samples/window/CMakeLists.txt
> +    string(REPLACE ";" " " "CMAKE_CXX_FLAGS" "${CMAKE_CXX_FLAGS}")
I took the code from base at that time, we edited it after but indeed I didn't apply the change here

2016-12-09 14:34 UTC, Sumenia commented on samples/window/main.cpp
> -
what is the need of using a vertical space here ?

2016-12-16 15:31 UTC, Quentin01 approved these changes

2016-12-16 15:31 UTC, Quentin01 commented on samples/window/main.cpp
> -
I don't know, but okay, this one is really useless

2016-12-16 15:38 UTC, merged