Feature keyboard event
Lugdunum3D/Lugdunum pull request #30
Opened 2017-02-05 16:16 UTC by saveman71

2017-02-06 08:49 UTC, Quentin01 requested changes

2017-02-06 08:49 UTC, Quentin01 commented on include/lug/Window/Event.hpp
> +#include <cstdint>
Order of includes (or we can do the meeting of the Guidelines as soon as possible)

2017-02-06 08:49 UTC, Quentin01 commented on include/lug/Window/Event.hpp
>  enum class LUG_WINDOW_API EventType : uint32_t {
We can maybe change that and put in the `Event` structure. And after that use it with `Event::Type`. Just to preserve the coherency of the code.

2017-02-06 08:49 UTC, Quentin01 commented on include/lug/Window/Event.hpp
> +    Close,          ///< Window close event
Why do you use this kind of comments, starting with `///<`?

2017-02-06 08:49 UTC, Quentin01 commented on include/lug/Window/Keyboard.hpp
> +#ifdef LUG_SYSTEM_WINDOWS
To preserve the coherency of the code, use `#if defined(...)`

2017-02-06 08:49 UTC, Quentin01 commented on include/lug/Window/Keyboard.hpp
> +#ifdef LUG_SYSTEM_LINUX
I prefer to have an `#elif` and a final `#else` with a clear error message

2017-02-06 08:49 UTC, Quentin01 commented on samples/window/main.cpp
> +#include <unordered_map>
Double include of `unordered_map`

2017-02-06 08:49 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +        // It would be nice to actually find a good solution to this problem.
Maybe add a TODO

2017-02-06 08:49 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +
Empty line at the end of the file

2017-02-06 08:49 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +Keyboard::Key vkToLugKey(WPARAM key) {
`static` function? Do you want to access it outside of this file?

2017-02-06 08:49 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +Keyboard::Key keysymToLugKey(KeySym key) {
`static` function? Do you want to access it outside of this file?

2017-02-06 08:49 UTC, Quentin01 commented on src/lug/Window/Window.cpp
>  #endif
Don't we need a final `#else` with an explicit message?

2017-02-06 08:49 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +        else if (event.type == EventType::KeyReleased) {
`else if` at the end of the previous line

2017-02-06 08:49 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +
Empty line at the end of the file

2017-02-21 08:55 UTC, Quentin01 requested changes

2017-02-21 08:55 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +#include <lug/System/Logger.hpp>
Order of include

2017-02-21 08:55 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +{
Bracket at the end of the previous line

2017-02-21 08:55 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +Window::Window(Window&& rhs) : _impl{rhs._impl} {
If think that we can't delete movable operators from `Window` since we handle them exclusively with `std::unique_ptr`

2017-02-22 05:49 UTC, Quentin01 approved these changes

2017-02-22 14:05 UTC, Nokitoo commented on samples/window/main.cpp
> +#include <lug/Window/Keyboard.hpp>
Order of includes

2017-02-22 14:05 UTC, Nokitoo commented on src/lug/Window/CMakeLists.txt
> +    ${INCROOT}/Keyboard.hpp
Order of include files

2017-02-22 14:05 UTC, Nokitoo commented on src/lug/Window/Win32/WindowImplWin32.cpp
> + //   case WM_SYSCHAR:
Comment not indented correctly + should be written `Case`

2017-02-22 14:05 UTC, Nokitoo commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +        // not a key we map from generic to left/right specialized
Missing uppercase to first letter of comment

2017-02-22 19:19 UTC, merged