Feature mouse event
Lugdunum3D/Lugdunum pull request #34
Opened 2017-04-26 13:42 UTC by StuartSulaski

2017-04-26 14:21 UTC, Quentin01 requested changes

2017-04-26 14:21 UTC, Quentin01 commented on include/lug/Window/Event.hpp
> +    bool alt;                              ///< True if alt was pressed, False otherwise
There is a problem of indentation for the comments. The same applies for the comments in `MouseEvent`.

2017-04-26 14:21 UTC, Quentin01 commented on include/lug/Window/Event.hpp
> +    union {
Use vertical spaces to between `struct` and `union` according to the guidelines.

2017-04-26 14:21 UTC, Quentin01 commented on include/lug/Window/Event.hpp
> +        MouseLeave,
Missing comments for `MouseLeave` and `MouseEnter`

2017-04-26 14:21 UTC, Quentin01 commented on include/lug/Window/Event.hpp
> +        MouseWheel,     ///< MouseWheelRotated event
There is a problem of indentation for the comment.

2017-04-26 14:21 UTC, Quentin01 commented on include/lug/Window/Event.hpp
> +        MouseEvent button;      ///< A MouseEvent
I don't think `button` is a good name for this one. Maybe `mouse`.

2017-04-26 14:21 UTC, Quentin01 commented on include/lug/Window/Event.hpp
> +    bool lMouse;   ///< True if left mouse button was pressed, False otherwise
Why do you need to suffix all the buttoons with `Mouse`? I don't think it's the right solution.

2017-04-26 14:21 UTC, Quentin01 commented on include/lug/Window/Mouse.hpp
> +    ENUM_LENGTH
Why `ENUM_LENGTH`?

2017-04-26 14:21 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    void getMousePos(uint32_t & x, uint32_t & y) const;
We don't use spaces between the type and `&` or `*` in the guidelines.

2017-04-26 14:21 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    * @param[in]  x   The parametre that will be set to the mouse's position on the x axis.
`parameter` maybe?

2017-04-26 14:21 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    * Ued to store the mouse's position, used by #getMousePos.
`Used`

2017-04-26 14:21 UTC, Quentin01 commented on samples/window/main.cpp
> +//            // Checking to see if mouse position is stored correctly
Do we need to keep this source code in comment?

2017-04-26 14:21 UTC, Quentin01 commented on samples/window/main.cpp
> +                    logger->info("MODIFIER CTRL");
Do we need this text? If yes, maybe we can change it to something more "esthetic".

2017-04-26 14:21 UTC, Quentin01 commented on samples/window/main.cpp
> +                logger->info("Mouse scroll wheel offset {} {}", event.button.scrollOffset.xOffset, event.button.scrollOffset.yOffset);
See the guidelines concerning vertical spaces. You need to indent between `if`.

2017-04-26 14:21 UTC, Quentin01 commented on samples/window/main.cpp
> +//            // Checking MouseMoved events
Do we need to keep this source code in comment?

2017-04-26 14:21 UTC, Quentin01 commented on samples/window/main.cpp
> +//        // Checking that mouse button states are correctly set
Do we need to keep this source code in comment?

2017-04-26 14:21 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +    /*int minor = XkbMinorVersion;
Why have you comment that?
Maybe we can just remove it.

2017-04-26 14:21 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +static Mouse::Button buttoncodeToLugButton(unsigned int buttoncode) {
`buttonCodeToLugButton` isn't better?

2017-04-26 14:21 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +            event.button.coord.x = xEvent.xbutton.x;
Use vertical space after `switch`

2017-04-26 14:21 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +            else {
Put `else` on the previous line

2017-04-26 14:21 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +//    if (message == WM_MOUSEWHEEL) {
Maybe remove this code.

2017-04-26 14:21 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +                    event.button.scrollOffset.xOffset = 0;
Can't you have the exact offset of the scroll like in Windows?

2017-04-26 14:21 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +    Window::Window() : _impl{new priv::WindowImpl(this)} {
Why do you have add an indentation?

2017-04-26 14:21 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +{
Bracket at the end of the previous line.

2017-04-26 14:21 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +        else if (event.type == Event::Type::ButtonReleased) {
`else if` at the end of the previous line.

2017-04-28 19:01 UTC, AlexandreQuivy commented on src/lug/Window/Unix/WindowImplX11.cpp
> +                    event.button.scrollOffset.xOffset = 0;
No, the wheel is like a classic button on X11.

2017-04-30 11:17 UTC, Quentin01 approved these changes

2017-04-30 11:37 UTC, merged