Debug asserts and breakpoints
Lugdunum3D/Lugdunum pull request #4
Opened 2016-10-06 17:21 UTC by saveman71

Test main:
```
#include <lug/Config.hpp>
#include <lug/System/Debug.hpp>

int main() {
    LUG_ASSERT(1 == 1, "not functionning");
    std::cout << "hello" << std::endl;
    return 0;
}
```

* Asserts and breakpoints are disabled on release
* **Not** tested on windows

2016-10-06 23:45 UTC, Quentin01 requested changes

2016-10-06 23:45 UTC, Quentin01 commented on include/lug/System/Utils.hpp
> +#if defined(__clang__) || defined(__GNUC__)
I think that LUG_LIKELY and LUG_UNLIKELY must stay in Debug.hpp. When to use them outside the debug?

2016-10-06 23:56 UTC, saveman71 commented on include/lug/System/Utils.hpp
> +#if defined(__clang__) || defined(__GNUC__)
My opinion is that it's a way to do an explicit optimization for likeliness check so it may be used elsewhere.

2016-10-07 00:27 UTC, Quentin01 approved these changes

2016-10-09 18:35 UTC, saveman71 commented
Status of this PR:

* [ ] Tests on windows

2016-10-13 19:05 UTC, saveman71 commented
Update: works on Windows, it triggers a breakpoint inside Visual Studio as expected

2016-10-14 05:15 UTC, merged