Create builders for Vulkan::API objects
Lugdunum3D/Lugdunum pull request #42
Opened 2017-05-07 17:00 UTC by Quentin01

2017-05-07 19:52 UTC, saveman71 submitted a review, later dismissed

2017-05-11 15:32 UTC, saveman71 requested changes

2017-05-11 15:32 UTC, saveman71 commented on include/lug/Graphics/Vulkan/API/Builder/Device.hpp
> +    void setExtensions(std::vector<const char*> extensions);
Add `// Setters` comment

2017-05-11 15:32 UTC, saveman71 commented on include/lug/Graphics/Vulkan/API/Builder/Device.hpp
> +    Device(PhysicalDeviceInfo& physicalDeviceInfo);
`const&`

2017-05-11 15:32 UTC, saveman71 commented on src/lug/Graphics/Vulkan/API/Builder/Device.cpp
> +    if (!queueFound && (queueFlags & VK_QUEUE_TRANSFER_BIT))
`) {`

2017-05-11 15:32 UTC, saveman71 commented on src/lug/Graphics/Vulkan/API/Builder/Device.cpp
> +    if (!queueFound)
`) {`

2017-05-11 15:43 UTC, saveman71 submitted a review, later dismissed

2017-05-30 13:20 UTC, Nokitoo approved these changes

2017-05-30 13:27 UTC, merged