Feature window
Lugdunum3D/Lugdunum pull request #5
Opened 2016-10-08 19:18 UTC by StuartSulaski

It's a window abstraction, yay

2016-10-09 07:13 UTC, Quentin01 requested changes
A lot of comments, please respect the guidelines :(

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/EventType.hpp
> +	CLOSE
**/!\ The indentation uses 4 spaces and not a tab (the same applies for all your source files). /!\**

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/EventType.hpp
> +};
New line at end of file

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/EventType.hpp
> +enum LUG_WINDOW_API EventType
`enum class`

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Remove this useless comment

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +#include <lug/Window/EventType.hpp>
Bad order of inclusion

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +		// le nom de ce namespace est le m�me que la SFML, je trouve �a tr�s bien comme nom, je penses que sans l'influence de la SFML je l'aurais appel� "private" donc bon :)
Remove this useless comment

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +		// on ne sait pas a quoi �a correspond pour le moment, donc on le forward declare
Remove this useless comment

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +		// a quoi ressemble un event pour l'utilisateur ? :D
Remove this useless comment

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +	struct LUG_WINDOW_API Event
Maybe put this in `EventType.hpp` and rename the file `Event.hpp` ?

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/EventType.hpp
> +enum LUG_WINDOW_API EventType
Namespace?

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +	enum LUG_WINDOW_API Style
What is the meaning of this enum which aren't used? (And `enum class`)

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +		private:
For what reason do you have an empty `private` section?

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +			Window(); // This should be private
So, make it `private`

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +			static std::unique_ptr<Window> create(int width, int height, const std::string& title, uint32_t style); // Cette fonction appel createWindow ce qui instancie l'impl�mentation de la fen�tre
Bad order of declaration (see the guidelines)

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +			priv::WindowImpl *_impl; // notre impl�mentation, pour le moment on a juste forward d�clar� priv::WindowImpl car on sait pas a quoi il correspond ici
Remove this useless comment

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +			std::queue<Event> _events; // notre queue d'event qui sont process par l'impl�mentation
Remove this useless comment

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +} // namespace lug
New line at end of file

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/CMakeLists.txt
> +
Why this vertical space?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/CMakeLists.txt
> +
Why this vertical space?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/CMakeLists.txt
> +    ${INCROOT}/EventType.hpp
Alphabetic order please

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +#include <queue>
Alphabetic order please

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +{}
New line at end of file

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +        WindowImpl();
Why not `= default`?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +        ~WindowImpl();
Why not `= default`?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +#include <X11/Xlib.h>
For what reason do you include that here? If you don't use an header in this file, don't include it in it.

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +    class WindowImpl
Vertical space please

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +    };
Vertical space please

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +        bool create(int width, int height, const std::string& title, uint32_t style);
"int" for a size? Use an uint32_t

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +bool lug::Window::priv::WindowImpl::create(int width, int height, const std::string& title, uint32_t style)
"int" for a size? Use an uint32_t

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +bool lug::Window::priv::WindowImpl::create(int width, int height, const std::string& title, uint32_t style)
For what reason style is an uint32_t? (It's not an enum?)

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +        bool create(int width, int height, const std::string& title, uint32_t style);
For what reason style is an uint32_t? (It's not an enum?)

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +bool lug::Window::priv::WindowImpl::create(int /*width*/, int /*height*/, const std::string & /*title*/, uint32_t /*style*/){
"int" for a size? Use an uint32_t

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +		static bool create(int width, int height, const std::string& title, uint32_t style);
"int" for a size? Use an uint32_t

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +bool lug::Window::priv::WindowImpl::create(int /*width*/, int /*height*/, const std::string & /*title*/, uint32_t /*style*/){
For what reason style is an uint32_t? (It's not an enum?)

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +		static bool create(int width, int height, const std::string& title, uint32_t style);
For what reason style is an uint32_t? (It's not an enum?)

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +		static bool create(int width, int height, const std::string& title, uint32_t style);
Why this member function is static?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +
So much horizontal space

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +
So much horizontal space

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +	class WindowImpl // WindowImplWin32
Maybe an horizontal space?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +	};
Maybe an horizontal space?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +	class WindowImpl // WindowImplWin32
Do not indent after a namespace

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +    class WindowImpl
Do not indent after a namespace

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Remove this useless comment

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +// on inclus la d�claration de lug::Window::priv::WindowImpl
Remove this useless comment

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +#include <iostream>
Just why?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +#include <lug/Window/Win32/WindowImplWin32.hpp>
Indent

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +#include <lug/Window/Unix/WindowImplX11.hpp>
Indent

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +#include <lug/Window/Android/WindowImplAndroid.hpp>
Indent

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +#include "..\..\..\..\include\lug\Window\Win32\WindowImplWin32.hpp"
Why?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +	return _impl->create(width, height, title, style);
You don't check if _impl is nullptr?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +	return (_impl != nullptr ? (true) : (false));
Why all these parentheses around true and false?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +	std::unique_ptr<Window> win = std::make_unique<Window>();
Just use `std::make_unique<Window>(new Window());` if the constructor is protected or private ;)

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +	// peut �tre que l'impl�mentation attend juste qu'on lui demande de process ses events, donc on appelle le process
Remove this useless comment

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +	// apr�s le possible process, si la queue est plus empty on peut en retourner un, sinon on retourne false
Remove this useless comment

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +		_impl->processEvents(_events);
You don't check if _impl is nullptr?

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/main.cpp
> +#include <lug/Window/Window.hpp>
Remove this useless file (use a new sample if you want)
And please, make a decent example, not one with a `while (1)` :)

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +bool lug::Window::Window::createWindow(int width, int height, const std::string & title, uint32_t style)
"int" for a size? Use an uint32_t

2016-10-09 07:13 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +std::unique_ptr<lug::Window::Window> lug::Window::Window::create(int width, int height, const std::string & title, uint32_t style)
"int" for a size? Use an uint32_t

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +			static std::unique_ptr<Window> create(int width, int height, const std::string& title, uint32_t style); // Cette fonction appel createWindow ce qui instancie l'impl�mentation de la fen�tre
"int" for a size? Use an uint32_t

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +			bool createWindow(int width, int height, const std::string& title, uint32_t style);
"int" for a size? Use an uint32_t

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +			bool createWindow(int width, int height, const std::string& title, uint32_t style);
For what reason style is an uint32_t? (It's not an enum?)

2016-10-09 07:13 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +			static std::unique_ptr<Window> create(int width, int height, const std::string& title, uint32_t style); // Cette fonction appel createWindow ce qui instancie l'impl�mentation de la fen�tre
For what reason style is an uint32_t? (It's not an enum?)

2016-10-09 07:37 UTC, Quentin01 requested changes

2016-10-09 07:37 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +lug::Window::Window::Window() : _impl(new lug::Window::priv::WindowImpl())
Where is the destructor which delete this pointer and close the window?

2016-10-09 07:43 UTC, mapy69003 commented on include/lug/Window/EventType.hpp
> +	CLOSE
It's @StuartSulaski faults !

2016-10-09 07:49 UTC, saveman71 requested changes
Overall remove all french comments from the PR. for useful comments, translate them to english, and try to remove any formal vocabulary please :)

2016-10-09 07:49 UTC, saveman71 commented on include/lug/Window/Window.hpp
> +	};
Please align the comments, at least the 5 firsts. And do not try to make them *pretty* (`///<` is just `//`)

Did it for you:
```
        None = 0,               // No border / title bar (this flag and all others are mutually exclusive)
        Titlebar = 1 << 0,      // Title bar + fixed border
        Resize = 1 << 1,        // Title bar + resizable border + maximize button
        Close = 1 << 2,         // Title bar + close button
        Fullscreen = 1 << 3,    // Fullscreen mode (this flag and all others are mutually exclusive)

        Default = Titlebar | Resize | Close     // Default window style
```

2016-10-09 07:49 UTC, saveman71 commented on include/lug/Window/Window.hpp
> +			Window(); // This should be private
(and remove the comment)

2016-10-09 07:49 UTC, saveman71 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +bool lug::Window::priv::WindowImpl::create(int width, int height, const std::string& title, uint32_t style)
I believe uint16_t is more appropriate? Can window size really exceed 65,535 by 65,535? (honest question here).

2016-10-09 07:49 UTC, saveman71 commented on src/lug/Window/Window.cpp
> +	return (_impl != nullptr ? (true) : (false));
Around return as well I think

2016-10-09 07:49 UTC, saveman71 commented on src/lug/Window/Window.cpp
> +bool lug::Window::Window::createWindow(int width, int height, const std::string & title, uint32_t style)
`{` at the end of the function, not after newline

2016-10-09 07:49 UTC, saveman71 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +lug::Window::priv::WindowImpl::WindowImpl(){
space between `()` and `{`. Same remark for other places.

2016-10-09 07:49 UTC, saveman71 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +{
`() {}`

same remark for other places in this PR, but will not comment each time

2016-10-09 07:49 UTC, saveman71 commented on src/lug/Window/Window.cpp
> +#include <lug/Window/Win32/WindowImplWin32.hpp>
indent

2016-10-09 07:56 UTC, saveman71 commented on include/lug/Window/Window.hpp
> +	struct LUG_WINDOW_API Event
No indent here

2016-10-09 08:08 UTC, mapy69003 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +bool lug::Window::priv::WindowImpl::create(int width, int height, const std::string& title, uint32_t style)
Yes it can, if I have 35 monitors

2016-10-09 08:27 UTC, mapy69003 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +#include <windows.h>
Why include windows.h if you don't use it ?

2016-10-09 08:27 UTC, mapy69003 commented on src/lug/Window/Window.cpp
> +	return _impl->create(width, height, title, style);
It is checked by the function that calls Window::createWindow() ... apparently

2016-10-09 09:57 UTC, Quentin01 requested changes

2016-10-09 09:57 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +namespace priv {
Vertical space

2016-10-09 09:57 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    bool createWindow(uint16_t width, uint16_t height, const std::string& title, uint32_t style);
Make this member function private too

2016-10-09 09:57 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +public:
Verticale space before `public`?

2016-10-09 09:57 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    bool createWindow(uint16_t width, uint16_t height, const std::string& title, uint32_t style);
`uint32_t` is used instead of `Style`

2016-10-09 09:57 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    bool closeWindow();
Just `close`

2016-10-09 09:57 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    static std::unique_ptr<Window> create(uint16_t width, uint16_t height, const std::string& title, uint32_t style);
`uint32_t` is used instead of `Style`

2016-10-09 09:57 UTC, Quentin01 commented on include/lug/Window/WindowHandle.hpp
> +#if defined(LUG_SYSTEM_WINDOWS)
Merge this condition with the next one

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/CMakeLists.txt
> +
Why this new vertical space?

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/CMakeLists.txt
> +
Remove that newline

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +bool lug::Window::priv::WindowImpl::create(uint16_t width, uint16_t height, const std::string& title, uint32_t style)
`uint32_t` is used instead of `Style`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +    bool create(uint16_t width, uint16_t height, const std::string& title, uint32_t style);
`uint32_t` is used instead of `Style`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +bool lug::Window::priv::WindowImpl::create(uint16_t /*width*/, uint16_t /*height*/, const std::string & /*title*/, uint32_t /*style*/)
`uint32_t` is used instead of `Style`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +	bool create(uint16_t width, uint16_t height, const std::string& title, uint32_t style);
`uint32_t` is used instead of `Style`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +std::unique_ptr<lug::Window::Window> lug::Window::Window::create(uint16_t width, uint16_t height, const std::string & title, uint32_t style)
`uint32_t` is used instead of `Style`

2016-10-09 09:57 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +{
Make the first bracket at the end of the last line.
That applies for all your source codes even in if statement, etc. (**I have seen this a lots of time**)

2016-10-09 09:57 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +enum class LUG_WINDOW_API Style
You need to define bitwise operations, for example this code won't work.
`Style style = Style::Titlebar | Style::Resize;`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +class WindowImpl // WindowImplWin32
Vertical space

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +class WindowImpl
Vertical space

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +#include <windows.h>
Remove this if you don't use it

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +lug::Window::priv::WindowImpl::WindowImpl()
This function is defined as `default` in the .hpp, so just remove it from here

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +lug::Window::priv::WindowImpl::~WindowImpl()
This function is defined as `default` in the .hpp, so just remove it from here

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +} // namespace lug
New line at end of file

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +#include <lug/Window/Win32/WindowImplWin32.hpp>
Use 4 spaces to indent, not tabs

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +#pragma once
Use 4 spaces to indent, not tabs

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +    closeWindow();
I think that `closeWindow` had to be in the destructor ;)

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +    return false;
Call `_impl->close()`? And check if `_impl` is `nullptr`!

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +    if (_impl->create(width, height, title, style) == false)
Check if `_impl` is `nullptr`!

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +    if (_impl != nullptr)
This condition is useless, `delete nullptr` is okay.

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +bool lug::Window::Window::createWindow(uint16_t width, uint16_t height, const std::string & title, uint32_t style)
`uint32_t` is used instead of `Style`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +    #elif defined(LUG_SYSTEM_LINUX)
Don't indent `#elif` like that

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +    #elif defined(LUG_SYSTEM_ANDROID)
Don't indent `#elif` like that

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +    #include "lug/Window/Win32/WindowImplWin32.hpp"
`#include <lug/Window/Android/WindowImplAndroid.hpp>`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +bool lug::Window::priv::WindowImpl::create(uint16_t /*width*/, uint16_t /*height*/, const std::string & /*title*/, uint32_t /*style*/)
No space between the type and `&`

2016-10-09 09:57 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    priv::WindowImpl *_impl;
`priv::WindowImpl* _impl;`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +    void processEvents(std::queue<lug::Window::Event> &events);
`std::queue<lug::Window::Event>& events`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +	void processEvents(std::queue<lug::Window::Event> &events);
`std::queue<lug::Window::Event>& events`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +bool lug::Window::Window::createWindow(uint16_t width, uint16_t height, const std::string & title, uint32_t style)
No space between the type and `&`

2016-10-09 09:57 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    bool pollEvent(Event &event);
No space between the type and `&`
`Event& event`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +std::unique_ptr<lug::Window::Window> lug::Window::Window::create(uint16_t width, uint16_t height, const std::string & title, uint32_t style)
No space between the type and `&`

2016-10-09 09:57 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +bool lug::Window::Window::pollEvent(Event &event)
No space between the type and `&`

2016-10-09 18:16 UTC, saveman71 requested changes

2016-10-09 18:16 UTC, saveman71 commented on src/lug/Window/Window.cpp
> +    if (!win->createWindow(width, height, title, style))
Add brackets

2016-10-09 23:10 UTC, Quentin01 requested changes
Use functions, not class

2016-10-09 23:18 UTC, Quentin01 requested changes

2016-10-09 23:18 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +private:
The public section must be before the private one.

2016-10-10 11:14 UTC, Quentin01 requested changes
#IAmAGrammarNazi

2016-10-10 11:14 UTC, Quentin01 commented on include/lug/Window/Event.hpp
> +enum class LUG_WINDOW_API EventType : uint32_t {
Vertical space before this enum

2016-10-10 11:14 UTC, Quentin01 commented on include/lug/Window/Event.hpp
> +}
New line at end of file

2016-10-10 11:14 UTC, Quentin01 commented on include/lug/Window/Style.inl
> +inline Style& operator|(Style& lhs, const Style& rhs) {
`inline Style operator|(const Style& lhs, const Style& rhs)` (Same for operators with `&` and `^`)
And maybe don't use reference with `Style` because `Style` is `uint16_t`

2016-10-10 11:14 UTC, Quentin01 commented on include/lug/Window/Style.inl
> +    return static_cast<Style&>(static_cast<Style&>(lhs) | static_cast<const Style&>(rhs));
`return static_cast<Style>(static_cast<uint16_t>(lhs) | static_cast<uint16_t>(rhs));` (Same for operators with `&` and `^`)

2016-10-10 11:14 UTC, Quentin01 commented on include/lug/Window/Style.inl
> +inline Style operator|=(Style& lhs, const Style& rhs) {
`inline Style& operator|=(Style& lhs, const Style& rhs)` (Same for operators with `&` and `^`)
And maybe don't use reference with `Style` because `Style` is `uint16_t`

2016-10-10 11:14 UTC, Quentin01 commented on include/lug/Window/Style.inl
> +    return (lhs = static_cast<Style&>(lhs) | static_cast<const Style&>(rhs));
`return (lhs = static_cast<Style>(static_cast<uint16_t>(lhs) | static_cast<uint16_t>(rhs)));` (Same for operators with `&` and `^`)

2016-10-10 11:14 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    bool close();
Does a `close` can fail? If not, do not return `bool`

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +bool lug::Window::priv::WindowImpl::close() {
Does a `close` can fail? If not, do not return `bool`

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.cpp
> +}
New line at end of file

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +namespace priv {
Why this vertical space before the namespace `priv`?

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +class WindowImpl {
Vertical space before a class

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +    bool close();
Does a `close` can fail? If not, do not return `bool`

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +class WindowImpl {
Where are the move constructor and move assignment operator? (`= delete` I think)

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Unix/WindowImplX11.hpp
> +    WindowImpl &operator=(WindowImpl&) = delete;
`&` attachs to the type

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +#include <lug/Window/Win32/WindowImplWin32.hpp>
Where is the close method?

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +class WindowImpl {
Vertical space before a class

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +class WindowImpl {
Where are the move constructor and the move assignment operator? (`= delete` I think)

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +    WindowImpl &operator=() = delete;
`&` attachs to the type

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +class WindowImpl {
Where is the `close` method?

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +private:
Vertical space before `private`

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Win32/WindowImplWin32.hpp
> +    bool create(uint16_t width, uint16_t height, const std::string& title, Style style);
For what reason `create` is private? `Window` can't call it!!

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +bool lug::Window::Window::isOpen( ) const {
No space inside parentheses

2016-10-10 11:14 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +bool lug::Window::Window::close() {
Does a `close` can fail? If not, do not return `bool`
I think that it doesn't matter if `_impl` is `nullptr` because the window is already closed.

2016-10-10 11:14 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    bool isOpen() const;
Vertical space after the destructor maybe?

2016-10-10 11:14 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +    bool createWindow(uint16_t width, uint16_t height, const std::string& title, Style style);
Vertical space after the constructor?

2016-10-10 11:21 UTC, Quentin01 requested changes
Not enough reviews :)

2016-10-10 11:21 UTC, Quentin01 commented on src/lug/Window/Window.cpp
> +bool lug::Window::Window::close() {
The condition in `isOpen()` is ` _impl != nullptr`
So I think that you have to delete `_impl` here and make it `nullptr`? (Update the destructor if that's the case)

2016-10-10 11:28 UTC, Quentin01 commented on include/lug/Window/Window.hpp
> +#include <lug/Window/Event.hpp>
Include `WindowHandle.hpp` because you will use it and that will check if its content compiles.

2016-10-10 14:25 UTC, Quentin01 submitted a review, later dismissed

2016-10-10 17:38 UTC, saveman71 requested changes

2016-10-10 17:38 UTC, saveman71 commented on src/lug/Window/CMakeLists.txt
> +	list(APPEND INC ${SRCROOT}/Unix/WindowImplX11.hpp)
Tabs -> spaces

2016-10-10 17:38 UTC, saveman71 commented on src/lug/Window/Win32/WindowImplWin32.cpp
> +bool lug::Window::priv::WindowImpl::create(uint16_t /*width*/, uint16_t /*height*/, const std::string & /*title*/, Style /*style*/) {
`const std::string&`

2016-10-10 17:38 UTC, saveman71 commented on src/lug/Window/Window.cpp
> +    return _impl != nullptr ? true : false;
`return _impl != nullptr;` should be enough ;)

2016-11-20 05:15 UTC, saveman71 approved these changes

2016-11-20 05:18 UTC, merged