build process android
Lugdunum3D/Lugdunum pull request #7
Opened 2016-10-12 21:20 UTC by Sumenia

This is the build process working for android Marshmallow and Nougat.
findLug doesn’t work within gradle so having lugdunum library install
in android/app/src/main/lugdunum is mandatory

Due to dynamic library dependancy policy in Android M, building
Lugdunum in static is mandatory.

also :
I removed weird broken ascii spaces across the project
Fixed the README.md

2016-10-12 22:09 UTC, saveman71 requested changes

2016-10-12 22:09 UTC, saveman71 commented on include/lug/System/Exception.hpp
> +class LUG_SYSTEM_API Exception: public std::exception  {
Two spaces?

2016-10-12 22:09 UTC, saveman71 commented on samples/base/CMakeLists.txt
> +    add_library( app-glue STATIC ${APP_GLUE_DIR}/android_native_app_glue.c)
Space after `(`

2016-10-12 22:09 UTC, saveman71 commented on samples/base/CMakeLists.txt
> -# project name
Why did you remove those lines?

2016-10-12 22:09 UTC, saveman71 commented on samples/base/CMakeLists.txt
> +                              app-glue
Indentation issue

2016-10-12 22:09 UTC, saveman71 commented on samples/base/CMakeLists.txt
> +if(NOT ANDROID)
Can you merge the two `NOT ANDROID` blocks in a single one?

2016-10-12 22:09 UTC, saveman71 commented on samples/base/main.cpp
> + #include <android/log.h>
4 spaces indent

2016-10-12 22:09 UTC, saveman71 commented on samples/base/main.cpp
> + #include "Lug/System/Exception.hpp"
Use `<>` for lug headers

2016-10-12 22:09 UTC, saveman71 commented on samples/base/main.cpp
> +    {
`{` goes at the end of previous lines. Applies to the `while` and the `if`s below too.

2016-10-12 22:09 UTC, saveman71 commented on src/lug/System/Exception.cpp
> +lug::System::Exception::Exception(const char *typeName, const std::string &description, const char* file, const char* function, uint32_t line) noexcept
Why? (4 spaces ident is lost, and the guidelines are not respected anymore)

2016-10-12 22:09 UTC, saveman71 commented on samples/base/main.cpp
> + #define LOGV(...)  ((void)__android_log_print(ANDROID_LOG_VERBOSE, "lugdunum sample", __VA_ARGS__))
You define `LOGV` but do not use it

2016-10-12 22:09 UTC, saveman71 commented on samples/base/main.cpp
> +#if defined(__ANDROID__)
You should define `LUG_SYSTEM_ANDROID` in `include/lug/Config.hpp` instead of using directly `__ANDROID__`

2016-10-13 03:54 UTC, Quentin01 requested changes
Where is lug-main?

2016-10-13 03:54 UTC, Quentin01 commented on CMakeLists.txt
> +if(ANDROID)
Why not using the same check than in `Config.cmake`?

2016-10-13 03:54 UTC, Quentin01 commented on CMakeLists.txt
> +if(ANDROID)
Maybe some vertical spaces in this block?

2016-10-13 03:54 UTC, Quentin01 commented on CMakeLists.txt
> +    set(ANDROID_ABI arm64-v8a)
So, the user haven't the choice?

2016-10-13 03:54 UTC, Quentin01 commented on CMakeLists.txt
> +    if(NOT ANDROID_PLATFORM MATCHES android-2[3-4])
In the future with `android-25`, what will you do?

2016-10-13 03:54 UTC, Quentin01 commented on CMakeLists.txt
> +    if(ANDROID_PLATFORM MATCHES android-23)
Don't you want to also use `c++_static` in case of platform 23?

2016-10-13 03:54 UTC, Quentin01 commented on cmake/modules/FindLUG.cmake
> +    message(STATUS "Found Lugdunum in ${LUG_LIBRARIES}")
Maybe don't use the message twice?

2016-10-13 03:54 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> -if(NOT CMAKE_BUILD_TYPE)
For what reason do you have remove that? You may need this for the Android Build

2016-10-13 03:54 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> -set(EXECUTABLE_NAME "base")
Why don't you use this one for the Android build too?

2016-10-13 03:54 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +    add_library( app-glue STATIC ${APP_GLUE_DIR}/android_native_app_glue.c)
No space after `(`

2016-10-13 03:54 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +    set(LUG_DIR ${CMAKE_CURRENT_SOURCE_DIR}/android/app/src/main/lugdunum)
Maybe use the same convention, so `LUG_ROOT` as everywhere

2016-10-13 03:54 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +    add_library( # Sets the name of the library : must match the name defined in AndroidManifest.xml
No space after `(`. I doubt of the usefulness of those comments except the one for `AndroidManifest.xml`.

2016-10-13 03:54 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +                              ${LUG_DIR}/lib/liblug-system-s-d.a)
So, you only use the debug library.
Use CMAKE_BUILD_TYPE to choose which one you want.

2016-10-13 03:54 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +        add_library(lug-system-d
So, you only use the debug library.
Use CMAKE_BUILD_TYPE to choose which one you want.

2016-10-13 03:54 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +        add_library(lug-system-d
And why all those newlines? That seems clear without.

2016-10-13 03:54 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +                              ${LUG_DIR}/lib/arm64-v8a/liblug-system-d.so)
So, you only use the debug library.
Use CMAKE_BUILD_TYPE to choose which one you want.

2016-10-13 03:54 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +        set_target_properties(# Specifies the target library.
Same question, why those newlines?

2016-10-13 03:54 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +                              lug-system-d)
So, you only use the debug library.
Use CMAKE_BUILD_TYPE to choose which one you want.

2016-10-13 04:07 UTC, Sumenia commented on CMakeLists.txt
> +    set(ANDROID_ABI arm64-v8a)
Nope. Android N and Vulkan are both arm64-v8a. There is no new arm architecture at this moment, not even planned. i guess we're good

2016-10-13 04:10 UTC, Sumenia commented on CMakeLists.txt
> +    if(NOT ANDROID_PLATFORM MATCHES android-2[3-4])
We have a full year ahead of us to even starting thinking to handle that.
I can modify for [2-9] if you want to have 5 more years planned

2016-10-13 04:12 UTC, Sumenia commented on cmake/modules/FindLUG.cmake
> +    message(STATUS "Found Lugdunum in ${LUG_LIBRARIES}")
Which one do we change ? The first one by "Lugdunum headers" ?

2016-10-13 12:26 UTC, Quentin01 commented on cmake/modules/FindLUG.cmake
> +    message(STATUS "Found Lugdunum in ${LUG_LIBRARIES}")
Yes, "Lugdunum headers" seems good.

2016-10-21 04:06 UTC, saveman71 approved these changes

2016-10-21 07:28 UTC, Quentin01 requested changes

2016-10-21 07:28 UTC, Quentin01 commented on CMakeLists.txt
> +    message(STATUS "ANDROID_TOOLCHAIN : ${ANDROID_TOOLCHAIN} ")
Space at the end of the message

2016-10-21 07:28 UTC, Quentin01 commented on cmake/modules/FindLUG.cmake
> +    ${ANDROID_NDK}/sources/lugdunum
Maybe also use the environnement variable?

2016-10-21 07:28 UTC, Quentin01 commented on include/lug/Main/Export.hpp
> +#pragma once
Useless file

2016-10-21 07:28 UTC, Quentin01 commented on include/lug/Main/MainAndroid.hpp
> +#include <android/native_activity.h>
Bad order of inclusion, include thread and mutex before.

2016-10-21 07:28 UTC, Quentin01 commented on include/lug/Main/MainAndroid.hpp
> +    std::mutex _mutex;
Explicit name for the mutex? What is it purpose?

2016-10-21 07:28 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +   list(APPEND CMAKE_CXX_FLAGS "-Wall -Wextra")
And "-Werror" ?

2016-10-21 07:28 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +find_package(LUG REQUIRED)
Link with system too!

2016-10-21 07:28 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +if(NOT LUG_FOUND)
Not usefull, this error will already happens in the FindLUG.cmake

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/CMakeLists.txt
> +    list(APPEND CMAKE_CXX_FLAGS "-Wall -Wextra")
And "-Werror"?

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/CMakeLists.txt
> +        list(APPEND CMAKE_CXX_FLAGS "-std=c++14")
Maybe just use that method for the all project?

2016-10-21 07:28 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +        list(APPEND CMAKE_CXX_FLAGS "-std=c++14")
Maybe just use that method for the all project?

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/Main/CMakeLists.txt
> +    list(APPEND SRC ${SRCROOT}/MainWindows.cpp)
No MainWindows for the moment, so ...?
Make it or just remove the support for Windows now (because that will break the build on Windows)

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/Main/MainAndroid.cpp
> +    delete this;
I don't think deleting itself is a great idea

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/Main/MainAndroid.cpp
> +
Double vertical space?

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/Main/MainAndroid.cpp
> +        _savedState = ::operator new(savedStateSize);
Maybe allocate an array of uint8_t?

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/Main/MainAndroid.cpp
> +        ::operator delete(_savedState);
If you change the allocation, use `delete[]`

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/Main/MainAndroid.cpp
> +    : _activity(activity), _savedState(nullptr), _savedStateSize(0) {
Why not using default constructor for `_savedState` and `_savedStateSize`?

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/Main/MainAndroid.cpp
> +    : _activity(activity), _savedState(nullptr), _savedStateSize(0) {
Brackets instead of parentheses

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/Main/MainAndroid.cpp
> +        memcpy(_savedState, savedState, savedStateSize);
Prefix `memcpy` by `std::`

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/Main/MainAndroid.cpp
> +    t.detach();
Isn't there a better solution?

2016-10-21 07:28 UTC, Quentin01 commented on src/lug/Main/MainAndroid.cpp
> +
Double vertical space?

2016-10-21 07:28 UTC, Quentin01 commented on include/lug/Main/MainAndroid.hpp
> +#include <lug/Main/Export.hpp>
Useless include

2016-10-21 07:28 UTC, Quentin01 commented on include/lug/Main/MainAndroid.hpp
> +#include <thread>
Don't include thread if you aren't using it in the header! (Include it in the source file)

2016-10-21 13:48 UTC, saveman71 commented on src/lug/Main/MainAndroid.cpp
> +    delete this;
How would you implement it then? We have to alloc it to java in ANativeActivity_onCreate and it is guaranteed that shutdowApplication is in fact, putting the application down for real. If we don't delete ourselves, we leak some memory

2016-10-21 13:49 UTC, saveman71 commented on src/lug/Main/MainAndroid.cpp
> +    t.detach();
After this function the thread is completely independent (Should *not* be joined), and we hand the main thread back to java. Do _you_ have a better solution in mind?

2016-10-21 13:57 UTC, saveman71 commented on samples/base/CMakeLists.txt
> +find_package(LUG REQUIRED)
And why? Currently the sample doesn't use any functionality from system.

2016-10-21 14:05 UTC, Sumenia commented on cmake/modules/FindLUG.cmake
> +    ${ANDROID_NDK}/sources/lugdunum
didn't we did this together ? That was the problem why FingLug failed when invoked by Android Studio

2016-10-21 15:48 UTC, Sumenia commented on include/lug/System/Exception.hpp
> +    Exception(const char *typeName, const std::string &description, const char* file, const char* function, uint32_t line) noexcept;
@Quentin01 should i fix this in this branch or create another branch about this issue and further tests of Exception on Android when this one is merged ?

2016-10-21 17:50 UTC, Quentin01 requested changes

2016-10-21 17:50 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +   list(APPEND CMAKE_CXX_FLAGS "-Wall -Wextra -Werror")
Missing one space

2016-10-21 17:50 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +find_package(LUG REQUIRED)
This sample is just a test and a demonstration for the user, so we can make it obvious that he needs to tell which librairies he wants.

2016-10-21 17:50 UTC, Quentin01 commented on samples/base/CMakeLists.txt
> +        list(APPEND CMAKE_CXX_FLAGS "-std=c++14")
Use that for all the project and remove `CMAKE_CXX_STANDARD 14`

2016-10-21 17:50 UTC, Quentin01 commented on include/lug/Main/MainAndroid.hpp
> +#pragma once
Does the user needs that file? If not move it to the src directory.

2016-10-21 19:37 UTC, Quentin01 approved these changes

2016-10-21 19:38 UTC, merged