Memory allocators
Lugdunum3D/Lugdunum pull request #9
Opened 2016-10-14 15:02 UTC by Quentin01

Just an example ;)
`#include <iostream>
#include <string>

#include <lug/Config.hpp>
#include <lug/System/Memory.hpp>
#include <lug/System/Memory/Area/Stack.hpp>
#include <lug/System/Memory/Allocator/Basic.hpp>
#include <lug/System/Memory/Allocator/Linear.hpp>

using BasicArena = lug::System::Memory::Arena<lug::System::Memory::Allocator::Basic>;
using LinearArena = lug::System::Memory::Arena<lug::System::Memory::Allocator::Linear>;

template<size_t size>
using StackArea = lug::System::Memory::Area::Stack<size>;

int main() {
    StackArea<4096> area;
    LinearArena arena(&area);

    //BasicArena arena;

    int* ptr = LUG_NEW(int, arena)(42);

    if (!ptr) {
        std::cerr << "Can't allocate memory" << std::endl;
        return 1;
    }

    std::cout << ptr << std::endl;
    std::cout << *ptr << std::endl;

    LUG_DELETE(ptr, arena);

    int* ptr2 = LUG_NEW_ARRAY(int[3], arena);

    if (!ptr2) {
        std::cerr << "Can't allocate memory" << std::endl;
        return 1;
    }

    ptr2[0] = 24;
    ptr2[1] = 42;
    ptr2[2] = 34;

    std::cout << ptr2 << std::endl;
    std::cout << ptr2[0] << std::endl;
    std::cout << ptr2[1] << std::endl;
    std::cout << ptr2[2] << std::endl;

    LUG_DELETE_ARRAY(ptr2, arena);

    std::string *ptr3 = LUG_NEW_ARRAY(std::string[3], arena);

    if (!ptr3) {
        std::cerr << "Can't allocate memory" << std::endl;
        return 1;
    }

    ptr3[0] = "hello";
    ptr3[1] = "world";
    ptr3[2] = "!";

    std::cout << ptr3 << std::endl;
    std::cout << ptr3[0] << std::endl;
    std::cout << ptr3[1] << std::endl;
    std::cout << ptr3[2] << std::endl;

    std::cout << reinterpret_cast<size_t*>(ptr3)[-1] << std::endl;

    LUG_DELETE_ARRAY(ptr3, arena);

    return 0;
}
`

2016-10-14 15:47 UTC, saveman71 requested changes

2016-10-14 15:47 UTC, saveman71 commented on src/lug/System/Memory/Allocator/Basic.cpp
> +void lug::System::Memory::Allocator::Basic::free(void *ptr) const {
`void* ptr`

2016-10-14 15:47 UTC, saveman71 commented on include/lug/System/Memory/Area/IArea.hpp
> +    void *start;
`void* start`

2016-10-14 15:47 UTC, saveman71 commented on include/lug/System/Memory/Area/IArea.hpp
> +    void *end;
`void* end`

2016-10-14 15:47 UTC, saveman71 commented on include/lug/System/Memory/Area/IArea.hpp
> +    Page *next;
`Page* next`

2016-10-14 15:47 UTC, saveman71 commented on include/lug/System/Memory/Arena.hpp
> +    void* allocate(size_t size, size_t alignment, const char* file, int line);
`int` => `size_t`

2016-10-14 15:47 UTC, saveman71 commented on include/lug/System/Memory/Allocator/Basic.hpp
> +    void free(void *ptr) const;
`void* ptr`

2016-10-14 15:47 UTC, saveman71 commented on include/lug/System/Memory/Allocator/Linear.hpp
> +    void free(void *ptr) const;
`void* ptr`

2016-10-14 15:47 UTC, saveman71 commented on src/lug/System/Memory/Allocator/Linear.cpp
> +void lug::System::Memory::Allocator::Linear::free(void *ptr) const {
`void* ptr`

2016-10-14 15:47 UTC, saveman71 commented on src/lug/System/CMakeLists.txt
> +    ${INCROOT}/Memory/Arena.hpp
Alphabetic order, Arena goes after Allocator

2016-10-14 15:47 UTC, saveman71 commented on include/lug/System/Memory.inl
> +    void* ptr = arena.allocate(sizeof(T) * nb + sizeof(size_t), alignment > alignof(size_t) ? (alignment - alignof(size_t)) : alignof(size_t), file, line);
Maybe this line is a little long, so an if could be better

2016-10-14 15:47 UTC, saveman71 commented on include/lug/System/Memory/Allocator/Basic.hpp
> +class LUG_SYSTEM_API Basic {
Maybe create a parent class so your templated class `Arena` can inherit of it?

2016-10-14 16:01 UTC, Quentin01 commented on include/lug/System/Memory/Allocator/Basic.hpp
> +class LUG_SYSTEM_API Basic {
Using an interface is just constraining (for const, etc) in this case.

2016-10-22 13:49 UTC, saveman71 requested changes

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory/Allocator/Basic.hpp
> +    size_t getSize(void *ptr) const;
`void* ptr`

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory/FreeList.hpp
> +    bool grow(void* start, void *end, size_t alignment, size_t offset);
`void* end`

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory/FreeList.hpp
> +    void free(void *ptr);
`void* ptr`

2016-10-22 13:49 UTC, saveman71 commented on src/lug/System/Memory/Allocator/Basic.cpp
> +size_t lug::System::Memory::Allocator::Basic::getSize(void *ptr) const {
`void* ptr`

2016-10-22 13:49 UTC, saveman71 commented on src/lug/System/Memory/Allocator/Linear.cpp
> +size_t lug::System::Memory::Allocator::Linear::getSize(void *ptr) const {
`void* ptr`

2016-10-22 13:49 UTC, saveman71 commented on src/lug/System/Memory/Allocator/Stack.cpp
> +size_t lug::System::Memory::Allocator::Stack::getSize(void *ptr) const {
`void* ptr`

2016-10-22 13:49 UTC, saveman71 commented on src/lug/System/Memory/FreeList.cpp
> +bool lug::System::Memory::FreeList::grow(void* start, void *end, size_t alignment, size_t offset) {
`void* end`

2016-10-22 13:49 UTC, saveman71 commented on src/lug/System/Memory/FreeList.cpp
> +        Element *it = static_cast<Element*>(start);
`Element* it`

2016-10-22 13:49 UTC, saveman71 commented on src/lug/System/Memory/FreeList.cpp
> +void lug::System::Memory::FreeList::free(void *ptr) {
`void* ptr`

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory.hpp
> +#define LUG_DELETE_ARRAY(object, arena) ::lug::System::Memory::delete_array(object, arena)
This is for all above lines:

Why are your prefixing lug with `::`? We didn't do that for other files

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory.hpp
> +}
Add `// priv` to indicate that you are closing the namespace. Apply for all files in the review. It's difficult without indentation for a reader to understand quickly what are these brackets for.

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory.inl
> +    for (size_t i = 0; i < nb; ++i)
If you decided to add brackets to single line `ifs`, do so for single line `for`

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory.inl
> +    for (size_t i = nb; i > 0; --i)
Same

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory.inl
> +
Double new line

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory/Allocator/Chunk.inl
> +    LUG_ASSERT(MaxSize >= size, "Size of the allocation is greater than the chunk max size");
chunk's max size

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory/Allocator/Chunk.inl
> +    LUG_ASSERT(MaxAlignment >= alignment, "Alignment of the allocation is greater than the chunk max alignment");
chunk's max alignment

(maybe, I don't know, add the value of the alignment that was exceeded in the message)

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory/Allocator/Linear.hpp
> +    // Dangerous operations
Explain why?

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory/Area/GrowingHeap.inl
> +
newline?

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory/Area/Heap.inl
> +
newline?

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory/Area/IArea.hpp
> +// The areas had to set prev to the previous page and next to nullptr
English, do you speak it?

2016-10-22 13:49 UTC, saveman71 commented on include/lug/System/Memory/Arena.hpp
> +    explicit Arena(lug::System::Memory::Area::IArea* area);
I think you can use `Area::IArea* area`

2016-10-22 13:50 UTC, saveman71 commented
Also, in other parts of the project, we used namespaces in the CPP files as well. I think this simplifies the reading of the code, so I'd suggest you do as well, at least so it"s coherent with the general codebase!

2016-10-22 18:46 UTC, Quentin01 commented on include/lug/System/Memory.hpp
> +#define LUG_DELETE_ARRAY(object, arena) ::lug::System::Memory::delete_array(object, arena)
I have explain that in Slack, it's just in case if the macro is used in some namespace context we just use the namespace from the "root" namespace.

2016-10-22 18:50 UTC, Quentin01 commented on include/lug/System/Memory.inl
> +
It's for separating the unique_ptr stuffs from the general allocation stuffs.

2016-10-22 18:51 UTC, Quentin01 commented on include/lug/System/Memory/Allocator/Chunk.inl
> +    LUG_ASSERT(MaxAlignment >= alignment, "Alignment of the allocation is greater than the chunk max alignment");
I can't, for that I had to have a macro that allow formated message :) (like printf)

2016-10-22 18:52 UTC, Quentin01 commented on include/lug/System/Memory/Allocator/Linear.hpp
> +    // Dangerous operations
Hum ... That seems obvious, if you reset the allocator from a previous state and free the value after this mark that won't works.

2016-10-22 18:52 UTC, saveman71 commented on include/lug/System/Memory/Allocator/Chunk.inl
> +    LUG_ASSERT(MaxAlignment >= alignment, "Alignment of the allocation is greater than the chunk max alignment");
Oh yeah sorry thought it was already implemented

2016-10-22 18:53 UTC, Quentin01 commented on include/lug/System/Memory/Area/IArea.hpp
> +// The areas had to set prev to the previous page and next to nullptr
Sorry, I don't know the mistake?

2016-10-22 18:53 UTC, saveman71 commented on include/lug/System/Memory/Allocator/Linear.hpp
> +    // Dangerous operations
I meant in the comment, make it more explicit maybe

2016-10-22 18:53 UTC, saveman71 commented on include/lug/System/Memory/Area/IArea.hpp
> +// The areas had to set prev to the previous page and next to nullptr
I don't understand the meaning of both sentences soooo...

2016-10-23 18:29 UTC, saveman71 approved these changes

2016-10-23 22:06 UTC, merged